[package]
name = "rust-bluez"
version = "0.1.0"
authors = ["Micah Wylde <micah@micahw.com>"]

[dependencies]
dbus = "0.6.0"
libc = "0.2.33"
nix = "0.9.0"
bincode = "0.9.2"
serde = "1.0.21"
serde_derive = "1.0.21"
tokio-uds = "0.1"
bytes = "0.4"
futures = "0.1"
tokio-io = "0.1"
tokio-core = "0.1"
tokio-proto = "0.1"
tokio-service = "0.1"
log = "0.3.8"
env_logger = "0.4.3"

