[package]
name = "rumble"
version = "0.0.1"
authors = ["Micah Wylde <micah@micahw.com>"]
license = "MIT/Apache-2.0"
repository = "https://github.com/mwylde/rumble"
homepage = "https://github.com/mwylde/rumble"

description = """
A Rust Bluetooth Low Energy (BLE) central module
library, currently supporting Linux/Bluez
"""

[dependencies]
libc = "0.2.33"
nix = "0.9.0"
bytes = "0.4"
num = "0.1.41"
log = "0.3.8"
env_logger = "0.4.3"
enum_primitive = "0.1.1"


[dependencies.nom]
version = "^3.2"
features = ["verbose-errors"]
